services:
  r-nox:
    image: r-nox
    build:
      context: .
      dockerfile: R-Nox/Dockerfile
  
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -N 1000
    environment:
      - POSTGRES_DB=r-nox
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - r-nox:/var/lib/postgresql/data

volumes:
  r-nox:
